SELECT SITE,
PRODUCT_TYPE,
  CASE
    WHEN PRODUCT_TYPE IN ('DIRECT', 'CARRITO') THEN 'MARKETPLACE'
    WHEN PRODUCT_TYPE IN ('API', 'COW', 'LINK', 'WALLET BUTTON',
                          'WALLET CONNECT', 'PREAPPROVAL', 
                          'LOYALTY', 'SUBSCRIPTION'
                          ) THEN 'ONLINE PAYMENTS'
    WHEN PRODUCT_TYPE IN ('MONEY TRANSFER', 'QR', 'QR-INTEROP',
                          'BOLETO', 'ACCOUNT FUND'
                         ) THEN 'WALLET'
    ELSE 'OTROS'
  END AS VERTICAL,
FECHA,
SUM(TPV) AS TPV,
USER_AGE,
RANGO_ASP
FROM `meli-bi-data.SBOX_PF_PAY_METRICS.APPROVAL_METRICS` app
WHERE 1=1
--AND FECHA >= '2023-01-01'
AND app.PAY_TRY_LAST = 1
GROUP BY ALL
ORDER BY 1,4